services:
  - type: web
    name: remindmylove
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: DATABASE_PATH
        value: /data/database.sqlite
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    # Automatic HTTPS/SSL
    domains:
      - remindmylove.onrender.com
    # Scale settings
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
databases:
  - name: remindmylove-db
    plan: free
    type: sqlite
    ipAllowList: []
